### ISSUE TITLE
sharing weights

### ISSUE THREAD

**Issue by Play2Boy** [JoinWei-PKU/GLAD#1]
hi, JoinWei, in your prototxt, three sub-network is stand-alone. But in your paper, the best performence is sharing weights. Because input data of three sub-network is different, I dont know how to handle it, could you tell me?

**Comment by JoinWei-PKU** [comment]
In my prototxt, I do share weights among four sub-networks. You can see the name of "param" for every layers. The same name means the weights are shared among these layers.

**Comment by Play2Boy** [comment]
oh, I did not realize that. Thank you very much.
